# Generated by Django 5.0.1 on 2024-01-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
    ]
